version: "3.6"
services:
  backend:
    image: ghcr.io/integratedproject-ii/back-end:main   
    ports: 
      - "3000:3000"  
networks:
    default:
        external:
            name: loykrathong_network
