version: "3.6"
services:
  backend:
    image: ghcr.io/integratedproject-ii/back-end:main   
    ports: 
      - "9000:9000"  
networks:
    default:
        external:
            name: loykrathong_network
